[package]
name = "test_attr"
version = "0.1.0"
authors = ["zgy"]
edition = "2018"


[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }